### ISSUE TITLE
Add `tinymce` as dependency?

### ISSUE THREAD

**Issue by GraemeWatt** [inveniosoftware/invenio-assets#163]
Dependabot opened a PR (HEPData/hepdata#742) to bump `invenio-assets` from 3.0.0 to 3.0.1, but the CI failed with error messages like:
```
ERROR in unable to locate '/opt/hostedtoolcache/Python/3.9.18/x64/var/hepdata-instance/assets/node_modules/tinymce/skins/content/default/content.css' glob
Error: unable to locate '/opt/hostedtoolcache/Python/3.9.18/x64/var/hepdata-instance/assets/node_modules/tinymce/skins/content/default/content.css' glob
    at CopyPlugin.runPattern (/opt/hostedtoolcache/Python/3.9.18/x64/var/hepdata-instance/assets/node_modules/copy-webpack-plugin/dist/index.js:407:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /opt/hostedtoolcache/Python/3.9.18/x64/var/hepdata-instance/assets/node_modules/copy-webpack-plugin/dist/index.js:747:28
```
For now, I fixed the problem on the HEPData side by adding `tinymce` as a dependency (https://github.com/HEPData/hepdata/pull/742/commits/00cadae792677a024d951fb72bfa35c28381f538).  But shouldn't `tinymce` be added as a dependency in `invenio_assets/assets/package.json` if it is needed to build the assets following the changes made in PR #161?

**Comment by GraemeWatt** [comment]
Closed by commit 9b15f2d98fe07dfa3484421c1bd5e331c7832936 made by @kpsherva included in v3.0.2 release.  Thanks!
